[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn edugame_backend.wsgi --bind 0.0.0.0:$PORT --log-level debug --capture-output --enable-stdio-inheritance"
healthcheckPath = "/api/health/"
releaseCommand = "python manage.py migrate --noinput"

