[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --fake-initial && python manage.py migrate api zero && python manage.py migrate && gunicorn edugame_backend.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health/"
